apiVersion: v1
kind: Namespace
metadata:
  name: ed-namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ed-jupyter-deployment
  namespace: ed-namespace
  labels:
    app: ed-jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ed-jupyter
  template:
    metadata:
      labels:
        app: ed-jupyter
    spec:
      containers:
      - name: ed-jupyter
        image: lipa142000/ed-2023:jupyter-latest
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
            
---

apiVersion: v1
kind: Service
metadata:
  name: ed-jupyter-service
  namespace: ed-namespace
spec:
  selector:
    app: ed-jupyter
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ed-jupyter-ingress
  namespace: ed-namespace
spec:
  rules:
  - host: jupyter.ed.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ed-jupyter-service
            port:
              number: 8888